name: Deploy to AWS with Terraform

on:
  workflow_run:
    workflows: ["Build and Push Microservices to Docker Hub"]
    types:
      - completed

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_producer_token: ${{ secrets.TOKEN }}
  TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Infrastructure Deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Terraform

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Extract Short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update image tags in Terraform
        run: |
          sed -i "s|\(image = \\\".*/microservice1:\).*\\\"|\1${SHORT_SHA}\\\"|" main.tf
          sed -i "s|\(image = \\\".*/microservice2:\).*\\\"|\1${SHORT_SHA}\\\"|" main.tf


      - name: Terraform Init with backend config
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET_NAME }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=us-west-1" \
            -backend-config="dynamodb_table=${{ secrets.TF_LOCK_TABLE_NAME }}" \
            -backend-config="encrypt=true"

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      # - name: Terraform des
      #   run: terraform destroy -auto-approve

        
