name: Build and Push Microservices to Docker Hub

on:
  push:
    branches:
      - master

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}


jobs:
  build-producer:
    name: Build and Push Producer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Producer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Producer Unit Tests
        run: |
          pip install -r tests/requirements.txt
          python -m unittest discover tests/

      - name: Start LocalStack for Producer Integration Tests
        run: docker run --rm -d -p 4566:4566 -p 4510-4559:4510-4559 --name localstack-producer localstack/localstack

      - name: Wait for LocalStack to be ready (Producer)
        run: sleep 10

      - name: Run Producer Integration Tests
        env:
          AWS_ACCESS_KEY_ID: test-p
          AWS_SECRET_ACCESS_KEY: test-p
          AWS_DEFAULT_REGION: us-west-1
          AWS_ENDPOINT_URL: http://localhost:4566
          SQS_QUEUE_URL: http://localhost:4566/000000000000/producer-integration-test-queue
        run: python -m unittest discover integration_tests/

      - name: Stop LocalStack (Producer)
        if: always()
        run: docker stop localstack-producer

      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Extract short SHA
        id: extract_sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $DOCKERHUB_USERNAME/microservice1:${SHORT_SHA} .

      - name: Push Docker image
        run: docker push $DOCKERHUB_USERNAME/microservice1:${SHORT_SHA}

  build-consumer:
    name: Build and Push Consumer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Consumer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Consumer Unit Tests
        run: |
          python -m unittest discover tests/

      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Extract short SHA
        id: extract_sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $DOCKERHUB_USERNAME/microservice2:${SHORT_SHA} .

      - name: Push Docker image
        run: docker push $DOCKERHUB_USERNAME/microservice2:${SHORT_SHA}
